services:
  ssh-tunnel:
    image: alpine:latest
    container_name: ssh_tunnel
    command: |
      sh -c "                                                                                                                                                                      
      apk add --no-cache openssh-client &&                
      ssh -D 0.0.0.0:10808 root@103.228.168.190 -N
      "
    ports:
      - "10808:10808"
    networks:
      - bot-network
    restart: unless-stopped

  bot:
    build: .
    depends_on:
      - ssh-tunnel
    env_file:
      - .env
    environment:
      - TG_PROXY=socks5://ssh-tunnel:10808
    volumes:
      - ./bot/logs:/app/logs
    networks:
      - bot-network
    restart: unless-stopped

  webhook:
    build:
      context: .
      dockerfile: webhook/Dockerfile.webhook
    container_name: deploy-webhook
    restart: always
    working_dir: /app
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    ports:
      - "9000:9000"
    command: python webhook/webhook.py
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge